// <auto-generated />
using CoreDB.DBLogApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreDB.Migrations
{
    [DbContext(typeof(DbLogAppContext))]
    [Migration("20250817025500_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_uca1400_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CoreDB.DBLogApp.AccountEntity", b =>
                {
                    b.Property<long>("pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("pid"));

                    b.Property<string>("name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("password")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("pid")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "name" }, "idx_name");

                    b.ToTable("AccountEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
