apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      initContainers:
      - name: docker-login 
        image: docker
        command: ["docker", "login", "-u", "rumdice", "-p", "duddns@554"] # docker 에 로그인 하기 위한 커맨드
      containers:
      - name: web-app-container
        image: rumdice/web-app:latest # docker hub 아이디/repository경로, docker build 시 tag로 지정합니다.
        ports:
        - containerPort: 8080 # 컨테이너의 포트 Dockerfile Expose로 명시
      imagePullSecrets:
      - name: rumdice-dockerhub-secret # docker hub private에 접근 하기 위한 kubectl secret 이름
        

---

apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 7002 # 로컬 포트(appsetting.json에 기록된 정보)
    targetPort: 8080 # 포트포워딩할 타겟 컨테이너의 포트, ContatinerPort와 일치 시킵니다.
  type: LoadBalancer

