FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5114

ENV ASPNETCORE_URLS=http://+:5114

USER app
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG configuration=Release
#WORKDIR /src
COPY ["AdminApp/AdminApp.csproj", "AdminApp/"]
RUN dotnet restore "AdminApp/AdminApp.csproj"
COPY . .
WORKDIR "/src/AdminApp"
RUN dotnet build "AdminApp.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "AdminApp.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "AdminApp.dll"]
